parameters:
#    charly_forum.example.class: Charly\ForumBundle\Example

services:
#    charly_forum.example:
#        class: %charly_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
